// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gr4vy/gr4vy-go/models/components"
)

type CreateThreeDsConfigurationRequest struct {
	// The ID of the merchant account.
	MerchantAccountID                         string                                               `pathParam:"style=simple,explode=false,name=merchant_account_id"`
	MerchantAccountThreeDSConfigurationCreate components.MerchantAccountThreeDSConfigurationCreate `request:"mediaType=application/json"`
}

func (c *CreateThreeDsConfigurationRequest) GetMerchantAccountID() string {
	if c == nil {
		return ""
	}
	return c.MerchantAccountID
}

func (c *CreateThreeDsConfigurationRequest) GetMerchantAccountThreeDSConfigurationCreate() components.MerchantAccountThreeDSConfigurationCreate {
	if c == nil {
		return components.MerchantAccountThreeDSConfigurationCreate{}
	}
	return c.MerchantAccountThreeDSConfigurationCreate
}
