// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gr4vy/gr4vy-go/models/components"
)

type CreateGiftCardGlobals struct {
	MerchantAccountID *string `header:"style=simple,explode=false,name=x-gr4vy-merchant-account-id"`
}

func (o *CreateGiftCardGlobals) GetMerchantAccountID() *string {
	if o == nil {
		return nil
	}
	return o.MerchantAccountID
}

type CreateGiftCardRequest struct {
	// The ID of the merchant account to use for this request.
	MerchantAccountID *string                   `header:"style=simple,explode=false,name=x-gr4vy-merchant-account-id"`
	GiftCardCreate    components.GiftCardCreate `request:"mediaType=application/json"`
}

func (o *CreateGiftCardRequest) GetMerchantAccountID() *string {
	if o == nil {
		return nil
	}
	return o.MerchantAccountID
}

func (o *CreateGiftCardRequest) GetGiftCardCreate() components.GiftCardCreate {
	if o == nil {
		return components.GiftCardCreate{}
	}
	return o.GiftCardCreate
}
