// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gr4vy/gr4vy-go/models/components"
)

type CreateGooglePayDigitalWalletSessionRequest struct {
	// The ID of the merchant account to use for this request.
	XGr4vyMerchantAccountID *string                            `header:"style=simple,explode=false,name=x-gr4vy-merchant-account-id"`
	GooglePaySessionRequest components.GooglePaySessionRequest `request:"mediaType=application/json"`
}

func (o *CreateGooglePayDigitalWalletSessionRequest) GetXGr4vyMerchantAccountID() *string {
	if o == nil {
		return nil
	}
	return o.XGr4vyMerchantAccountID
}

func (o *CreateGooglePayDigitalWalletSessionRequest) GetGooglePaySessionRequest() components.GooglePaySessionRequest {
	if o == nil {
		return components.GooglePaySessionRequest{}
	}
	return o.GooglePaySessionRequest
}

type CreateGooglePayDigitalWalletSessionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	GooglePaySession *components.GooglePaySession
}

func (o *CreateGooglePayDigitalWalletSessionResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateGooglePayDigitalWalletSessionResponse) GetGooglePaySession() *components.GooglePaySession {
	if o == nil {
		return nil
	}
	return o.GooglePaySession
}
