// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type CreatePaymentServiceSessionGlobals struct {
	MerchantAccountID *string `header:"style=simple,explode=false,name=x-gr4vy-merchant-account-id"`
}

func (o *CreatePaymentServiceSessionGlobals) GetMerchantAccountID() *string {
	if o == nil {
		return nil
	}
	return o.MerchantAccountID
}

type CreatePaymentServiceSessionRequest struct {
	// the ID of the payment service
	PaymentServiceID string `pathParam:"style=simple,explode=false,name=payment_service_id"`
	// The ID of the merchant account to use for this request.
	MerchantAccountID *string        `header:"style=simple,explode=false,name=x-gr4vy-merchant-account-id"`
	RequestBody       map[string]any `request:"mediaType=application/json"`
}

func (o *CreatePaymentServiceSessionRequest) GetPaymentServiceID() string {
	if o == nil {
		return ""
	}
	return o.PaymentServiceID
}

func (o *CreatePaymentServiceSessionRequest) GetMerchantAccountID() *string {
	if o == nil {
		return nil
	}
	return o.MerchantAccountID
}

func (o *CreatePaymentServiceSessionRequest) GetRequestBody() map[string]any {
	if o == nil {
		return map[string]any{}
	}
	return o.RequestBody
}
