// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gr4vy/gr4vy-go/internal/utils"
	"github.com/gr4vy/gr4vy-go/models/components"
)

type CreatePayoutRequest struct {
	TimeoutInSeconds *float64 `default:"1" queryParam:"style=form,explode=true,name=timeout_in_seconds"`
	// The ID of the merchant account to use for this request.
	XGr4vyMerchantAccountID *string                 `header:"style=simple,explode=false,name=x-gr4vy-merchant-account-id"`
	PayoutCreate            components.PayoutCreate `request:"mediaType=application/json"`
}

func (c CreatePayoutRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreatePayoutRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *CreatePayoutRequest) GetTimeoutInSeconds() *float64 {
	if o == nil {
		return nil
	}
	return o.TimeoutInSeconds
}

func (o *CreatePayoutRequest) GetXGr4vyMerchantAccountID() *string {
	if o == nil {
		return nil
	}
	return o.XGr4vyMerchantAccountID
}

func (o *CreatePayoutRequest) GetPayoutCreate() components.PayoutCreate {
	if o == nil {
		return components.PayoutCreate{}
	}
	return o.PayoutCreate
}

type CreatePayoutResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PayoutSummary *components.PayoutSummary
}

func (o *CreatePayoutResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreatePayoutResponse) GetPayoutSummary() *components.PayoutSummary {
	if o == nil {
		return nil
	}
	return o.PayoutSummary
}
