// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetBuyerGlobals struct {
	MerchantAccountID *string `header:"style=simple,explode=false,name=x-gr4vy-merchant-account-id"`
}

func (o *GetBuyerGlobals) GetMerchantAccountID() *string {
	if o == nil {
		return nil
	}
	return o.MerchantAccountID
}

type GetBuyerRequest struct {
	// The ID of the buyer to retrieve.
	BuyerID string `pathParam:"style=simple,explode=false,name=buyer_id"`
	// The ID of the merchant account to use for this request.
	MerchantAccountID *string `header:"style=simple,explode=false,name=x-gr4vy-merchant-account-id"`
}

func (o *GetBuyerRequest) GetBuyerID() string {
	if o == nil {
		return ""
	}
	return o.BuyerID
}

func (o *GetBuyerRequest) GetMerchantAccountID() *string {
	if o == nil {
		return nil
	}
	return o.MerchantAccountID
}
