// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetPaymentLinkGlobals struct {
	MerchantAccountID *string `header:"style=simple,explode=false,name=x-gr4vy-merchant-account-id"`
}

func (g *GetPaymentLinkGlobals) GetMerchantAccountID() *string {
	if g == nil {
		return nil
	}
	return g.MerchantAccountID
}

type GetPaymentLinkRequest struct {
	// The unique identifier for the payment link.
	PaymentLinkID string `pathParam:"style=simple,explode=false,name=payment_link_id"`
	// The ID of the merchant account to use for this request.
	MerchantAccountID *string `header:"style=simple,explode=false,name=x-gr4vy-merchant-account-id"`
}

func (g *GetPaymentLinkRequest) GetPaymentLinkID() string {
	if g == nil {
		return ""
	}
	return g.PaymentLinkID
}

func (g *GetPaymentLinkRequest) GetMerchantAccountID() *string {
	if g == nil {
		return nil
	}
	return g.MerchantAccountID
}
