// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gr4vy/gr4vy-go/internal/utils"
	"github.com/gr4vy/gr4vy-go/models/components"
)

type ListPaymentLinksGlobals struct {
	MerchantAccountID *string `header:"style=simple,explode=false,name=x-gr4vy-merchant-account-id"`
}

func (l *ListPaymentLinksGlobals) GetMerchantAccountID() *string {
	if l == nil {
		return nil
	}
	return l.MerchantAccountID
}

type ListPaymentLinksRequest struct {
	// A pointer to the page of results to return.
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
	// The maximum number of items that are returned.
	Limit *int64 `default:"20" queryParam:"style=form,explode=true,name=limit"`
	// Filters the results to only get the items for which some of the buyer data contains exactly the provided `buyer_search` values.
	BuyerSearch []string `queryParam:"style=form,explode=true,name=buyer_search"`
	// The ID of the merchant account to use for this request.
	MerchantAccountID *string `header:"style=simple,explode=false,name=x-gr4vy-merchant-account-id"`
}

func (l ListPaymentLinksRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListPaymentLinksRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListPaymentLinksRequest) GetCursor() *string {
	if l == nil {
		return nil
	}
	return l.Cursor
}

func (l *ListPaymentLinksRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListPaymentLinksRequest) GetBuyerSearch() []string {
	if l == nil {
		return nil
	}
	return l.BuyerSearch
}

func (l *ListPaymentLinksRequest) GetMerchantAccountID() *string {
	if l == nil {
		return nil
	}
	return l.MerchantAccountID
}

type ListPaymentLinksResponse struct {
	Result components.PaymentLinks

	Next func() (*ListPaymentLinksResponse, error)
}

func (l *ListPaymentLinksResponse) GetResult() components.PaymentLinks {
	if l == nil {
		return components.PaymentLinks{}
	}
	return l.Result
}
