// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gr4vy/gr4vy-go/internal/utils"
	"github.com/gr4vy/gr4vy-go/models/components"
)

type ListMerchantAccountsRequest struct {
	// A pointer to the page of results to return.
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
	// The maximum number of items that are at returned.
	Limit *int64 `default:"20" queryParam:"style=form,explode=true,name=limit"`
	// The search term to filter merchant accounts by.
	Search *string `queryParam:"style=form,explode=true,name=search"`
}

func (l ListMerchantAccountsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListMerchantAccountsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ListMerchantAccountsRequest) GetCursor() *string {
	if o == nil {
		return nil
	}
	return o.Cursor
}

func (o *ListMerchantAccountsRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ListMerchantAccountsRequest) GetSearch() *string {
	if o == nil {
		return nil
	}
	return o.Search
}

type ListMerchantAccountsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	CollectionMerchantAccount *components.CollectionMerchantAccount

	Next func() (*ListMerchantAccountsResponse, error)
}

func (o *ListMerchantAccountsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListMerchantAccountsResponse) GetCollectionMerchantAccount() *components.CollectionMerchantAccount {
	if o == nil {
		return nil
	}
	return o.CollectionMerchantAccount
}
