// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gr4vy/gr4vy-go/models/components"
)

type ListGiftCardBalancesGlobals struct {
	MerchantAccountID *string `header:"style=simple,explode=false,name=x-gr4vy-merchant-account-id"`
}

func (l *ListGiftCardBalancesGlobals) GetMerchantAccountID() *string {
	if l == nil {
		return nil
	}
	return l.MerchantAccountID
}

type ListGiftCardBalancesRequest struct {
	// The ID of the merchant account to use for this request.
	MerchantAccountID      *string                           `header:"style=simple,explode=false,name=x-gr4vy-merchant-account-id"`
	GiftCardBalanceRequest components.GiftCardBalanceRequest `request:"mediaType=application/json"`
}

func (l *ListGiftCardBalancesRequest) GetMerchantAccountID() *string {
	if l == nil {
		return nil
	}
	return l.MerchantAccountID
}

func (l *ListGiftCardBalancesRequest) GetGiftCardBalanceRequest() components.GiftCardBalanceRequest {
	if l == nil {
		return components.GiftCardBalanceRequest{}
	}
	return l.GiftCardBalanceRequest
}
