// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gr4vy/gr4vy-go/internal/utils"
	"github.com/gr4vy/gr4vy-go/models/components"
)

type UnregisterDigitalWalletDomainRequest struct {
	DigitalWalletID  string   `pathParam:"style=simple,explode=false,name=digital_wallet_id"`
	TimeoutInSeconds *float64 `default:"1" queryParam:"style=form,explode=true,name=timeout_in_seconds"`
	// The ID of the merchant account to use for this request.
	XGr4vyMerchantAccountID *string                        `header:"style=simple,explode=false,name=x-gr4vy-merchant-account-id"`
	DigitalWalletDomain     components.DigitalWalletDomain `request:"mediaType=application/json"`
}

func (u UnregisterDigitalWalletDomainRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UnregisterDigitalWalletDomainRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *UnregisterDigitalWalletDomainRequest) GetDigitalWalletID() string {
	if o == nil {
		return ""
	}
	return o.DigitalWalletID
}

func (o *UnregisterDigitalWalletDomainRequest) GetTimeoutInSeconds() *float64 {
	if o == nil {
		return nil
	}
	return o.TimeoutInSeconds
}

func (o *UnregisterDigitalWalletDomainRequest) GetXGr4vyMerchantAccountID() *string {
	if o == nil {
		return nil
	}
	return o.XGr4vyMerchantAccountID
}

func (o *UnregisterDigitalWalletDomainRequest) GetDigitalWalletDomain() components.DigitalWalletDomain {
	if o == nil {
		return components.DigitalWalletDomain{}
	}
	return o.DigitalWalletDomain
}

type UnregisterDigitalWalletDomainResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	Any any
}

func (o *UnregisterDigitalWalletDomainResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UnregisterDigitalWalletDomainResponse) GetAny() any {
	if o == nil {
		return nil
	}
	return o.Any
}
