// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/gr4vy/gr4vy-go/internal/utils"
	"github.com/gr4vy/gr4vy-go/types"
	"time"
)

type AccountUpdaterJob struct {
	// Always `account-updater-job`
	type_ *string `const:"account-updater-job" json:"type"`
	// The ID for the account updater job.
	ID string `json:"id"`
	// The ID of the merchant account this job belongs to.
	MerchantAccountID string `json:"merchant_account_id"`
	// A list of the payment methods that have been scheduled for an update.
	Inquiries []AccountUpdaterInquirySummary `json:"inquiries"`
	// The date and time when this payment method was first created in our system.
	CreatedAt time.Time `json:"created_at"`
	// The date and time when this payment method was last updated in our system.
	UpdatedAt time.Time `json:"updated_at"`
}

func (a AccountUpdaterJob) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccountUpdaterJob) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *AccountUpdaterJob) GetType() *string {
	return types.String("account-updater-job")
}

func (o *AccountUpdaterJob) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *AccountUpdaterJob) GetMerchantAccountID() string {
	if o == nil {
		return ""
	}
	return o.MerchantAccountID
}

func (o *AccountUpdaterJob) GetInquiries() []AccountUpdaterInquirySummary {
	if o == nil {
		return []AccountUpdaterInquirySummary{}
	}
	return o.Inquiries
}

func (o *AccountUpdaterJob) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *AccountUpdaterJob) GetUpdatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedAt
}
