// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/gr4vy/gr4vy-go/internal/utils"
	"github.com/gr4vy/gr4vy-go/types"
)

// AccountType - Specify whether this is a `checking` or `savings` account
type AccountType string

const (
	AccountTypeChecking AccountType = "checking"
	AccountTypeSavings  AccountType = "savings"
)

func (e AccountType) ToPointer() *AccountType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AccountType) IsExact() bool {
	if e != nil {
		switch *e {
		case "checking", "savings":
			return true
		}
	}
	return false
}

// ACHBankPaymentMethodCreate - ACH Bank Payment Method
//
// Bank Payment Method for ACH bank accounts.
type ACHBankPaymentMethodCreate struct {
	// Always `bank`.
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	method        *string           `const:"bank" json:"method"`
	AccountHolder BankAccountHolder `json:"account_holder"`
	// The ID of the buyer to attach the method to.
	BuyerID *string `json:"buyer_id,omitempty"`
	// The merchant reference for this payment method.
	BuyerExternalIdentifier *string `json:"buyer_external_identifier,omitempty"`
	// The merchant identifier for this payment method.
	ExternalIdentifier *string `json:"external_identifier,omitempty"`
	// Always `ach`.
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	scheme *string `const:"ach" json:"scheme"`
	// The account number for this ACH bank account
	AccountNumber string `json:"account_number"`
	// The routing number for this ACH bank account
	RoutingNumber string `json:"routing_number"`
	// Whether the account number is tokenized
	IsTokenized *bool `default:"false" json:"is_tokenized"`
	// Specify whether this is a `checking` or `savings` account
	AccountType AccountType `json:"account_type"`
}

func (a ACHBankPaymentMethodCreate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *ACHBankPaymentMethodCreate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, []string{"account_holder", "account_number", "routing_number", "account_type"}); err != nil {
		return err
	}
	return nil
}

func (a *ACHBankPaymentMethodCreate) GetMethod() *string {
	return types.Pointer("bank")
}

func (a *ACHBankPaymentMethodCreate) GetAccountHolder() BankAccountHolder {
	if a == nil {
		return BankAccountHolder{}
	}
	return a.AccountHolder
}

func (a *ACHBankPaymentMethodCreate) GetBuyerID() *string {
	if a == nil {
		return nil
	}
	return a.BuyerID
}

func (a *ACHBankPaymentMethodCreate) GetBuyerExternalIdentifier() *string {
	if a == nil {
		return nil
	}
	return a.BuyerExternalIdentifier
}

func (a *ACHBankPaymentMethodCreate) GetExternalIdentifier() *string {
	if a == nil {
		return nil
	}
	return a.ExternalIdentifier
}

func (a *ACHBankPaymentMethodCreate) GetScheme() *string {
	return types.Pointer("ach")
}

func (a *ACHBankPaymentMethodCreate) GetAccountNumber() string {
	if a == nil {
		return ""
	}
	return a.AccountNumber
}

func (a *ACHBankPaymentMethodCreate) GetRoutingNumber() string {
	if a == nil {
		return ""
	}
	return a.RoutingNumber
}

func (a *ACHBankPaymentMethodCreate) GetIsTokenized() *bool {
	if a == nil {
		return nil
	}
	return a.IsTokenized
}

func (a *ACHBankPaymentMethodCreate) GetAccountType() AccountType {
	if a == nil {
		return AccountType("")
	}
	return a.AccountType
}
