// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdyenPixOptions struct {
	// Passes additional data to the Adyen API when creating a transaction.
	AdditionalData map[string]string `json:"additionalData,omitempty"`
	// Passes `pixRecurring` data to Adyen
	PixRecurring *AdyenPixRecurringOptions `json:"pixRecurring,omitempty"`
}

func (a *AdyenPixOptions) GetAdditionalData() map[string]string {
	if a == nil {
		return nil
	}
	return a.AdditionalData
}

func (a *AdyenPixOptions) GetPixRecurring() *AdyenPixRecurringOptions {
	if a == nil {
		return nil
	}
	return a.PixRecurring
}
