// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/gr4vy/gr4vy-go/internal/utils"
	"github.com/gr4vy/gr4vy-go/types"
)

// BaseBankPaymentMethodCreate - Base class for Bank Payment Methods.
type BaseBankPaymentMethodCreate struct {
	// Always `bank`.
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	method        *string           `const:"bank" json:"method"`
	AccountHolder BankAccountHolder `json:"account_holder"`
	// The ID of the buyer to attach the method to.
	BuyerID *string `json:"buyer_id,omitempty"`
	// The merchant reference for this payment method.
	BuyerExternalIdentifier *string `json:"buyer_external_identifier,omitempty"`
	// The merchant identifier for this payment method.
	ExternalIdentifier *string `json:"external_identifier,omitempty"`
}

func (b BaseBankPaymentMethodCreate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BaseBankPaymentMethodCreate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, []string{"account_holder"}); err != nil {
		return err
	}
	return nil
}

func (b *BaseBankPaymentMethodCreate) GetMethod() *string {
	return types.Pointer("bank")
}

func (b *BaseBankPaymentMethodCreate) GetAccountHolder() BankAccountHolder {
	if b == nil {
		return BankAccountHolder{}
	}
	return b.AccountHolder
}

func (b *BaseBankPaymentMethodCreate) GetBuyerID() *string {
	if b == nil {
		return nil
	}
	return b.BuyerID
}

func (b *BaseBankPaymentMethodCreate) GetBuyerExternalIdentifier() *string {
	if b == nil {
		return nil
	}
	return b.BuyerExternalIdentifier
}

func (b *BaseBankPaymentMethodCreate) GetExternalIdentifier() *string {
	if b == nil {
		return nil
	}
	return b.ExternalIdentifier
}
