// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// BuyerUpdate - Request body for updating an existing buyer
type BuyerUpdate struct {
	// The display name for the buyer.
	DisplayName *string `json:"display_name,omitempty"`
	// The merchant identifier for this buyer.
	ExternalIdentifier *string `json:"external_identifier,omitempty"`
	// The buyer account number
	AccountNumber *string `json:"account_number,omitempty"`
	// The billing name, address, email, and other fields for this buyer.
	BillingDetails *BillingDetailsInput `json:"billing_details,omitempty"`
}

func (o *BuyerUpdate) GetDisplayName() *string {
	if o == nil {
		return nil
	}
	return o.DisplayName
}

func (o *BuyerUpdate) GetExternalIdentifier() *string {
	if o == nil {
		return nil
	}
	return o.ExternalIdentifier
}

func (o *BuyerUpdate) GetAccountNumber() *string {
	if o == nil {
		return nil
	}
	return o.AccountNumber
}

func (o *BuyerUpdate) GetBillingDetails() *BillingDetailsInput {
	if o == nil {
		return nil
	}
	return o.BillingDetails
}
