// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/gr4vy/gr4vy-go/internal/utils"
	"github.com/gr4vy/gr4vy-go/types"
)

type CardSchemeDefinition struct {
	// Always `card-scheme-definition`.
	type_ *string `const:"card-scheme-definition" json:"type"`
	// The ID for the card scheme.
	ID string `json:"id"`
	// The icon for this card scheme.
	IconURL string `json:"icon_url"`
	// The display name of this card scheme.
	DisplayName string `json:"display_name"`
}

func (c CardSchemeDefinition) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CardSchemeDefinition) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"id", "icon_url", "display_name"}); err != nil {
		return err
	}
	return nil
}

func (o *CardSchemeDefinition) GetType() *string {
	return types.String("card-scheme-definition")
}

func (o *CardSchemeDefinition) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *CardSchemeDefinition) GetIconURL() string {
	if o == nil {
		return ""
	}
	return o.IconURL
}

func (o *CardSchemeDefinition) GetDisplayName() string {
	if o == nil {
		return ""
	}
	return o.DisplayName
}
