// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/gr4vy/gr4vy-go/internal/utils"
	"github.com/gr4vy/gr4vy-go/types"
)

type CheckoutSessionPaymentMethodOutput struct {
	// Always `payment-method`
	type_ *string `const:"payment-method" json:"type"`
	// The ID of the payment method.
	ID *string `json:"id,omitempty"`
	// Details for credit or debit card payment method.
	Details *CheckoutSessionPaymentMethodDetails `json:"details,omitempty"`
	// The last 4 digits of the the card.
	Label *string `json:"label,omitempty"`
	// Always `card`
	method *string `const:"card" json:"method"`
	// The scheme of the card.
	Scheme *CardScheme `json:"scheme,omitempty"`
	// The unique hash derived from the card number.
	Fingerprint *string `json:"fingerprint,omitempty"`
}

func (c CheckoutSessionPaymentMethodOutput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CheckoutSessionPaymentMethodOutput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CheckoutSessionPaymentMethodOutput) GetType() *string {
	return types.Pointer("payment-method")
}

func (c *CheckoutSessionPaymentMethodOutput) GetID() *string {
	if c == nil {
		return nil
	}
	return c.ID
}

func (c *CheckoutSessionPaymentMethodOutput) GetDetails() *CheckoutSessionPaymentMethodDetails {
	if c == nil {
		return nil
	}
	return c.Details
}

func (c *CheckoutSessionPaymentMethodOutput) GetLabel() *string {
	if c == nil {
		return nil
	}
	return c.Label
}

func (c *CheckoutSessionPaymentMethodOutput) GetMethod() *string {
	return types.Pointer("card")
}

func (c *CheckoutSessionPaymentMethodOutput) GetScheme() *CardScheme {
	if c == nil {
		return nil
	}
	return c.Scheme
}

func (c *CheckoutSessionPaymentMethodOutput) GetFingerprint() *string {
	if c == nil {
		return nil
	}
	return c.Fingerprint
}
