// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ClickToPaySession struct {
	// The ID of the Click to Pay application.
	DigitalPaymentApplicationID string `json:"digital_payment_application_id"`
	// The merchant name as configured ont he the Click to Pay wallet.
	DigitalPaymentApplicationName string `json:"digital_payment_application_name"`
}

func (o *ClickToPaySession) GetDigitalPaymentApplicationID() string {
	if o == nil {
		return ""
	}
	return o.DigitalPaymentApplicationID
}

func (o *ClickToPaySession) GetDigitalPaymentApplicationName() string {
	if o == nil {
		return ""
	}
	return o.DigitalPaymentApplicationName
}
