// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/gr4vy/gr4vy-go/internal/utils"
)

type CollectionAPIKeyPair struct {
	// A list of items returned for this request.
	Items []APIKeyPair `json:"items"`
	// The number of items for this page.
	Limit *int64 `default:"20" json:"limit"`
	// The cursor pointing at the next page of items.
	NextCursor *string `json:"next_cursor,omitempty"`
	// The cursor pointing at the previous page of items.
	PreviousCursor *string `json:"previous_cursor,omitempty"`
}

func (c CollectionAPIKeyPair) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CollectionAPIKeyPair) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CollectionAPIKeyPair) GetItems() []APIKeyPair {
	if c == nil {
		return []APIKeyPair{}
	}
	return c.Items
}

func (c *CollectionAPIKeyPair) GetLimit() *int64 {
	if c == nil {
		return nil
	}
	return c.Limit
}

func (c *CollectionAPIKeyPair) GetNextCursor() *string {
	if c == nil {
		return nil
	}
	return c.NextCursor
}

func (c *CollectionAPIKeyPair) GetPreviousCursor() *string {
	if c == nil {
		return nil
	}
	return c.PreviousCursor
}
