// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/gr4vy/gr4vy-go/internal/utils"
	"github.com/gr4vy/gr4vy-go/types"
)

type Cryptogram struct {
	// Always `network-token-cryptogram`.
	type_ *string `const:"network-token-cryptogram" json:"type"`
	// The cryptogram of the network token.
	Cryptogram string `json:"cryptogram"`
}

func (c Cryptogram) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *Cryptogram) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *Cryptogram) GetType() *string {
	return types.Pointer("network-token-cryptogram")
}

func (c *Cryptogram) GetCryptogram() string {
	if c == nil {
		return ""
	}
	return c.Cryptogram
}
