// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CVVResponseCode string

const (
	CVVResponseCodeMatch       CVVResponseCode = "match"
	CVVResponseCodeNoMatch     CVVResponseCode = "no_match"
	CVVResponseCodeUnavailable CVVResponseCode = "unavailable"
	CVVResponseCodeNotProvided CVVResponseCode = "not_provided"
)

func (e CVVResponseCode) ToPointer() *CVVResponseCode {
	return &e
}
