// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DefinitionFieldFormat string

const (
	DefinitionFieldFormatText      DefinitionFieldFormat = "text"
	DefinitionFieldFormatMultiline DefinitionFieldFormat = "multiline"
	DefinitionFieldFormatNumber    DefinitionFieldFormat = "number"
	DefinitionFieldFormatTimezone  DefinitionFieldFormat = "timezone"
	DefinitionFieldFormatBoolean   DefinitionFieldFormat = "boolean"
)

func (e DefinitionFieldFormat) ToPointer() *DefinitionFieldFormat {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *DefinitionFieldFormat) IsExact() bool {
	if e != nil {
		switch *e {
		case "text", "multiline", "number", "timezone", "boolean":
			return true
		}
	}
	return false
}
