// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DigitalWalletProvider string

const (
	DigitalWalletProviderApple      DigitalWalletProvider = "apple"
	DigitalWalletProviderGoogle     DigitalWalletProvider = "google"
	DigitalWalletProviderClickToPay DigitalWalletProvider = "click-to-pay"
)

func (e DigitalWalletProvider) ToPointer() *DigitalWalletProvider {
	return &e
}
