// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DlocalOptions struct {
	// Passes `wallet` data to the dLocal API for those connectors that need it.
	Wallet *DlocalWalletOptions `json:"wallet,omitempty"`
}

func (o *DlocalOptions) GetWallet() *DlocalWalletOptions {
	if o == nil {
		return nil
	}
	return o.Wallet
}
