// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DlocalUPIWalletOptions struct {
	// Passes `wallet.name` to the dLocal API for those connectors that need it.
	Name *string `json:"name,omitempty"`
	// Passes `wallet.email` to the dLocal API for those connectors that need it.
	Email *string `json:"email,omitempty"`
	// Passes `wallet.token` to the dLocal API for those connectors that need it.
	Token *string `json:"token,omitempty"`
	// Passes `wallet.username` to the dLocal API for those connectors that need it.
	Username *string `json:"username,omitempty"`
	// Passes `wallet.verify` to the dLocal API for those connectors that need it.
	Verify *bool `json:"verify,omitempty"`
	// Passes `wallet.recurring_info` to the dLocal API for those connectors that need it.
	RecurringInfo *DlocalUPIRecurringInfoOptions `json:"recurring_info,omitempty"`
}

func (d *DlocalUPIWalletOptions) GetName() *string {
	if d == nil {
		return nil
	}
	return d.Name
}

func (d *DlocalUPIWalletOptions) GetEmail() *string {
	if d == nil {
		return nil
	}
	return d.Email
}

func (d *DlocalUPIWalletOptions) GetToken() *string {
	if d == nil {
		return nil
	}
	return d.Token
}

func (d *DlocalUPIWalletOptions) GetUsername() *string {
	if d == nil {
		return nil
	}
	return d.Username
}

func (d *DlocalUPIWalletOptions) GetVerify() *bool {
	if d == nil {
		return nil
	}
	return d.Verify
}

func (d *DlocalUPIWalletOptions) GetRecurringInfo() *DlocalUPIRecurringInfoOptions {
	if d == nil {
		return nil
	}
	return d.RecurringInfo
}
