// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// GiftCardTransactionCreate - Create a charge against a gift card
type GiftCardTransactionCreate struct {
	// The 16-19 digit number for the gift card.
	Number string `json:"number"`
	// The PIN for this gift card.
	Pin string `json:"pin"`
	// The monetary amount for this transaction to charge against the gift card, in the smallest currency unit (for example, cents or pence).
	Amount int64 `json:"amount"`
}

func (o *GiftCardTransactionCreate) GetNumber() string {
	if o == nil {
		return ""
	}
	return o.Number
}

func (o *GiftCardTransactionCreate) GetPin() string {
	if o == nil {
		return ""
	}
	return o.Pin
}

func (o *GiftCardTransactionCreate) GetAmount() int64 {
	if o == nil {
		return 0
	}
	return o.Amount
}
