// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/gr4vy/gr4vy-go/internal/utils"
)

// GiftCardActivationCreate - The details used to activate a physical gift card.
type GiftCardActivationCreate struct {
	// The 16-19 digit number for the gift card.
	Number string `json:"number"`
	// The PIN for this gift card.
	Pin *string `json:"pin,omitempty"`
	// The amount to load onto the gift card, in the smallest denomination for the currency. Required if `currency` is provided.
	Amount *int64 `json:"amount,omitempty"`
	// The ISO-4217 currency code for the `amount`. Required if `amount` is provided.
	Currency *string `json:"currency,omitempty"`
	// An optional external identifier for this activation.
	ExternalIdentifier *string `json:"external_identifier,omitempty"`
	// Whether to store the activated gift card in the vault. When `true`, a `pin` is required.
	Store *bool `default:"false" json:"store"`
	// The ID of the buyer to associate this gift card to. Only allowed when `store` is `true`. If this field is provided then the `buyer_external_identifier` field needs to be unset.
	BuyerID *string `json:"buyer_id,omitempty"`
	// The `external_identifier` of the buyer to associate this gift card to. Only allowed when `store` is `true`. If this field is provided then the `buyer_id` field needs to be unset.
	BuyerExternalIdentifier *string `json:"buyer_external_identifier,omitempty"`
}

func (g GiftCardActivationCreate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GiftCardActivationCreate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GiftCardActivationCreate) GetNumber() string {
	if g == nil {
		return ""
	}
	return g.Number
}

func (g *GiftCardActivationCreate) GetPin() *string {
	if g == nil {
		return nil
	}
	return g.Pin
}

func (g *GiftCardActivationCreate) GetAmount() *int64 {
	if g == nil {
		return nil
	}
	return g.Amount
}

func (g *GiftCardActivationCreate) GetCurrency() *string {
	if g == nil {
		return nil
	}
	return g.Currency
}

func (g *GiftCardActivationCreate) GetExternalIdentifier() *string {
	if g == nil {
		return nil
	}
	return g.ExternalIdentifier
}

func (g *GiftCardActivationCreate) GetStore() *bool {
	if g == nil {
		return nil
	}
	return g.Store
}

func (g *GiftCardActivationCreate) GetBuyerID() *string {
	if g == nil {
		return nil
	}
	return g.BuyerID
}

func (g *GiftCardActivationCreate) GetBuyerExternalIdentifier() *string {
	if g == nil {
		return nil
	}
	return g.BuyerExternalIdentifier
}
