// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GooglePaySession struct {
	// The gateway ID for the merchant as assigned by our platform.
	GatewayMerchantID string `json:"gateway_merchant_id"`
	// The session token for Google Pay.
	Token string `json:"token"`
}

func (o *GooglePaySession) GetGatewayMerchantID() string {
	if o == nil {
		return ""
	}
	return o.GatewayMerchantID
}

func (o *GooglePaySession) GetToken() string {
	if o == nil {
		return ""
	}
	return o.Token
}
