// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GuestBuyerInput struct {
	// The display name for the buyer.
	DisplayName *string `json:"display_name,omitempty"`
	// The merchant identifier for this buyer.
	ExternalIdentifier *string `json:"external_identifier,omitempty"`
	// The billing name, address, email, and other fields for this buyer.
	BillingDetails *BillingDetailsInput `json:"billing_details,omitempty"`
	// The buyer account number
	AccountNumber *string `json:"account_number,omitempty"`
	// The optional shipping details for this buyer.
	ShippingDetails *ShippingDetailsCreate `json:"shipping_details,omitempty"`
}

func (o *GuestBuyerInput) GetDisplayName() *string {
	if o == nil {
		return nil
	}
	return o.DisplayName
}

func (o *GuestBuyerInput) GetExternalIdentifier() *string {
	if o == nil {
		return nil
	}
	return o.ExternalIdentifier
}

func (o *GuestBuyerInput) GetBillingDetails() *BillingDetailsInput {
	if o == nil {
		return nil
	}
	return o.BillingDetails
}

func (o *GuestBuyerInput) GetAccountNumber() *string {
	if o == nil {
		return nil
	}
	return o.AccountNumber
}

func (o *GuestBuyerInput) GetShippingDetails() *ShippingDetailsCreate {
	if o == nil {
		return nil
	}
	return o.ShippingDetails
}
