// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GuestBuyerOutput struct {
	// The display name for the buyer.
	DisplayName *string `json:"display_name,omitempty"`
	// The merchant identifier for this buyer.
	ExternalIdentifier *string `json:"external_identifier,omitempty"`
	// The billing name, address, email, and other fields for this buyer.
	BillingDetails *BillingDetailsOutput `json:"billing_details,omitempty"`
	// The buyer account number
	AccountNumber *string `json:"account_number,omitempty"`
	// The optional shipping details for this buyer.
	ShippingDetails *ShippingDetailsCreate `json:"shipping_details,omitempty"`
}

func (o *GuestBuyerOutput) GetDisplayName() *string {
	if o == nil {
		return nil
	}
	return o.DisplayName
}

func (o *GuestBuyerOutput) GetExternalIdentifier() *string {
	if o == nil {
		return nil
	}
	return o.ExternalIdentifier
}

func (o *GuestBuyerOutput) GetBillingDetails() *BillingDetailsOutput {
	if o == nil {
		return nil
	}
	return o.BillingDetails
}

func (o *GuestBuyerOutput) GetAccountNumber() *string {
	if o == nil {
		return nil
	}
	return o.AccountNumber
}

func (o *GuestBuyerOutput) GetShippingDetails() *ShippingDetailsCreate {
	if o == nil {
		return nil
	}
	return o.ShippingDetails
}
