// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type IncrementalAuthorizationStatus string

const (
	IncrementalAuthorizationStatusSucceeded IncrementalAuthorizationStatus = "succeeded"
	IncrementalAuthorizationStatusFailed    IncrementalAuthorizationStatus = "failed"
)

func (e IncrementalAuthorizationStatus) ToPointer() *IncrementalAuthorizationStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *IncrementalAuthorizationStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "succeeded", "failed":
			return true
		}
	}
	return false
}
