// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LatitudeOptions struct {
	// The `promotionReference` field passed to the purchase API.
	PromotionReference *string `json:"promotion_reference,omitempty"`
}

func (l *LatitudeOptions) GetPromotionReference() *string {
	if l == nil {
		return nil
	}
	return l.PromotionReference
}
