// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PaymentMethodStatus string

const (
	PaymentMethodStatusProcessing            PaymentMethodStatus = "processing"
	PaymentMethodStatusBuyerApprovalRequired PaymentMethodStatus = "buyer_approval_required"
	PaymentMethodStatusSucceeded             PaymentMethodStatus = "succeeded"
	PaymentMethodStatusFailed                PaymentMethodStatus = "failed"
	PaymentMethodStatusPaused                PaymentMethodStatus = "paused"
)

func (e PaymentMethodStatus) ToPointer() *PaymentMethodStatus {
	return &e
}
