// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/gr4vy/gr4vy-go/internal/utils"
	"github.com/gr4vy/gr4vy-go/types"
	"time"
)

// PaymentMethod - Payment Method
//
// A stored payment method.
type PaymentMethod struct {
	// Always `payment-method`.
	type_ *string `const:"payment-method" json:"type"`
	// The optional URL that the buyer needs to be redirected to to further authorize their payment.
	ApprovalURL *string `json:"approval_url,omitempty"`
	// The 2-letter ISO code of the country this payment method can be used for. If this value is null the payment method may be used in multiple countries.
	Country *string `json:"country,omitempty"`
	// The ISO-4217 currency code that this payment method can be used for. If this value is null the payment method may be used for multiple currencies.
	Currency *string `json:"currency,omitempty"`
	// Details for credit or debit card payment method.
	Details *PaymentMethodDetailsCard `json:"details,omitempty"`
	// The expiration date for the payment method.
	ExpirationDate *string `json:"expiration_date,omitempty"`
	// The unique hash derived from the payment method identifier (e.g. card number).
	Fingerprint *string `json:"fingerprint,omitempty"`
	// A label for the card or the account. For a paypal payment method this is the user's email address. For a card it is the last 4 digits of the card.
	Label *string `json:"label,omitempty"`
	// The date and time when this card was last replaced by the account updater.
	LastReplacedAt *time.Time `json:"last_replaced_at,omitempty"`
	Method         Method     `json:"method"`
	// The mode to use with this payment method.
	Mode *Mode `json:"mode,omitempty"`
	// The scheme of the card. Only applies to card payments.
	Scheme *CardScheme `json:"scheme,omitempty"`
	// The ID for the payment method.
	ID string `json:"id"`
	// The ID of the merchant account this buyer belongs to.
	MerchantAccountID string `json:"merchant_account_id"`
	// Additional schemes of the card besides the primary scheme. Only applies to card payment methods.
	AdditionalSchemes []CardScheme `json:"additional_schemes,omitempty"`
	// The timestamp when this payment method was last used in a transaction for client initiated transactions.
	CitLastUsedAt *time.Time `json:"cit_last_used_at,omitempty"`
	// The number of times this payment method has been used in transactions for client initiated transactions.
	CitUsageCount int64 `json:"cit_usage_count"`
	// Whether this card has a pending replacement that hasn't been applied yet.
	HasReplacement bool `json:"has_replacement"`
	// The timestamp when this payment method was last used in a transaction.
	LastUsedAt *time.Time `json:"last_used_at,omitempty"`
	// The number of times this payment method has been used in transactions.
	UsageCount int64 `json:"usage_count"`
	// The optional buyer for which this payment method has been stored.
	Buyer *Buyer `json:"buyer,omitempty"`
	// The merchant reference that can be used to match the payment method against your own records.
	ExternalIdentifier *string             `json:"external_identifier,omitempty"`
	Status             PaymentMethodStatus `json:"status"`
	// The date and time when this payment method was first created in our system.
	CreatedAt time.Time `json:"created_at"`
	// The date and time when this payment method was last updated in our system.
	UpdatedAt time.Time `json:"updated_at"`
}

func (p PaymentMethod) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PaymentMethod) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"method", "id", "merchant_account_id", "cit_usage_count", "has_replacement", "usage_count", "status", "created_at", "updated_at"}); err != nil {
		return err
	}
	return nil
}

func (o *PaymentMethod) GetType() *string {
	return types.String("payment-method")
}

func (o *PaymentMethod) GetApprovalURL() *string {
	if o == nil {
		return nil
	}
	return o.ApprovalURL
}

func (o *PaymentMethod) GetCountry() *string {
	if o == nil {
		return nil
	}
	return o.Country
}

func (o *PaymentMethod) GetCurrency() *string {
	if o == nil {
		return nil
	}
	return o.Currency
}

func (o *PaymentMethod) GetDetails() *PaymentMethodDetailsCard {
	if o == nil {
		return nil
	}
	return o.Details
}

func (o *PaymentMethod) GetExpirationDate() *string {
	if o == nil {
		return nil
	}
	return o.ExpirationDate
}

func (o *PaymentMethod) GetFingerprint() *string {
	if o == nil {
		return nil
	}
	return o.Fingerprint
}

func (o *PaymentMethod) GetLabel() *string {
	if o == nil {
		return nil
	}
	return o.Label
}

func (o *PaymentMethod) GetLastReplacedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.LastReplacedAt
}

func (o *PaymentMethod) GetMethod() Method {
	if o == nil {
		return Method("")
	}
	return o.Method
}

func (o *PaymentMethod) GetMode() *Mode {
	if o == nil {
		return nil
	}
	return o.Mode
}

func (o *PaymentMethod) GetScheme() *CardScheme {
	if o == nil {
		return nil
	}
	return o.Scheme
}

func (o *PaymentMethod) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *PaymentMethod) GetMerchantAccountID() string {
	if o == nil {
		return ""
	}
	return o.MerchantAccountID
}

func (o *PaymentMethod) GetAdditionalSchemes() []CardScheme {
	if o == nil {
		return nil
	}
	return o.AdditionalSchemes
}

func (o *PaymentMethod) GetCitLastUsedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.CitLastUsedAt
}

func (o *PaymentMethod) GetCitUsageCount() int64 {
	if o == nil {
		return 0
	}
	return o.CitUsageCount
}

func (o *PaymentMethod) GetHasReplacement() bool {
	if o == nil {
		return false
	}
	return o.HasReplacement
}

func (o *PaymentMethod) GetLastUsedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.LastUsedAt
}

func (o *PaymentMethod) GetUsageCount() int64 {
	if o == nil {
		return 0
	}
	return o.UsageCount
}

func (o *PaymentMethod) GetBuyer() *Buyer {
	if o == nil {
		return nil
	}
	return o.Buyer
}

func (o *PaymentMethod) GetExternalIdentifier() *string {
	if o == nil {
		return nil
	}
	return o.ExternalIdentifier
}

func (o *PaymentMethod) GetStatus() PaymentMethodStatus {
	if o == nil {
		return PaymentMethodStatus("")
	}
	return o.Status
}

func (o *PaymentMethod) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *PaymentMethod) GetUpdatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedAt
}
