// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PaymentServiceConfiguration struct {
	ApprovalUITarget ApprovalTarget `json:"approval_ui_target"`
	// Height of the approval interface in either pixels or view height (vh).
	ApprovalUIHeight string `json:"approval_ui_height"`
	// Width of the approval interface in either pixels or view width (vw).
	ApprovalUIWidth string `json:"approval_ui_width"`
	// The maximum number of cart items supported by this connector before we will truncate the list.
	CartItemsLimit int64 `json:"cart_items_limit"`
	// Defines if cart items are required by this connector.
	CartItemsRequired bool `json:"cart_items_required"`
	// Defines if the cart items sum value should match the transaction amount.
	CartItemsShouldMatchAmount bool `json:"cart_items_should_match_amount"`
}

func (o *PaymentServiceConfiguration) GetApprovalUITarget() ApprovalTarget {
	if o == nil {
		return ApprovalTarget("")
	}
	return o.ApprovalUITarget
}

func (o *PaymentServiceConfiguration) GetApprovalUIHeight() string {
	if o == nil {
		return ""
	}
	return o.ApprovalUIHeight
}

func (o *PaymentServiceConfiguration) GetApprovalUIWidth() string {
	if o == nil {
		return ""
	}
	return o.ApprovalUIWidth
}

func (o *PaymentServiceConfiguration) GetCartItemsLimit() int64 {
	if o == nil {
		return 0
	}
	return o.CartItemsLimit
}

func (o *PaymentServiceConfiguration) GetCartItemsRequired() bool {
	if o == nil {
		return false
	}
	return o.CartItemsRequired
}

func (o *PaymentServiceConfiguration) GetCartItemsShouldMatchAmount() bool {
	if o == nil {
		return false
	}
	return o.CartItemsShouldMatchAmount
}
