// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PaymentOptions struct {
	// A list of items returned for this request.
	Items []PaymentOption `json:"items"`
}

func (p *PaymentOptions) GetItems() []PaymentOption {
	if p == nil {
		return []PaymentOption{}
	}
	return p.Items
}
