// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PayoutStatus string

const (
	PayoutStatusDeclined  PayoutStatus = "declined"
	PayoutStatusFailed    PayoutStatus = "failed"
	PayoutStatusPending   PayoutStatus = "pending"
	PayoutStatusSucceeded PayoutStatus = "succeeded"
)

func (e PayoutStatus) ToPointer() *PayoutStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PayoutStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "declined", "failed", "pending", "succeeded":
			return true
		}
	}
	return false
}
