// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PaypalShippingOptionsItemType string

const (
	PaypalShippingOptionsItemTypeShipping         PaypalShippingOptionsItemType = "SHIPPING"
	PaypalShippingOptionsItemTypePickup           PaypalShippingOptionsItemType = "PICKUP"
	PaypalShippingOptionsItemTypePickupInStore    PaypalShippingOptionsItemType = "PICKUP_IN_STORE"
	PaypalShippingOptionsItemTypePickupFromPerson PaypalShippingOptionsItemType = "PICKUP_FROM_PERSON"
)

func (e PaypalShippingOptionsItemType) ToPointer() *PaypalShippingOptionsItemType {
	return &e
}

type PaypalShippingOptionsItem struct {
	// A unique ID that identifies a payer-selected shipping option.
	ID string `json:"id"`
	// A description that the payer sees, which helps them choose an appropriate shipping option.
	Label string `json:"label"`
	// If the API request sets selected = true, it represents the shipping option that the payee or merchant expects to be pre-selected for the payer when they first view the shipping.options in the PayPal Checkout experience. Only one shipping.option can be set to selected=true.
	Selected bool `json:"selected"`
	// A classification for the method of purchase fulfillment.
	Type *PaypalShippingOptionsItemType `json:"type,omitempty"`
	// The shipping cost for the selected option.
	Amount *PaypalShippingOptionsItemAmount `json:"amount,omitempty"`
}

func (p *PaypalShippingOptionsItem) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PaypalShippingOptionsItem) GetLabel() string {
	if p == nil {
		return ""
	}
	return p.Label
}

func (p *PaypalShippingOptionsItem) GetSelected() bool {
	if p == nil {
		return false
	}
	return p.Selected
}

func (p *PaypalShippingOptionsItem) GetType() *PaypalShippingOptionsItemType {
	if p == nil {
		return nil
	}
	return p.Type
}

func (p *PaypalShippingOptionsItem) GetAmount() *PaypalShippingOptionsItemAmount {
	if p == nil {
		return nil
	}
	return p.Amount
}
