// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PazeCobrandItem struct {
	// Product name of the cobrand card. Must match exactly with the card name from the network.
	Name string `json:"name"`
	// Whether benefits are offered for this cobrand card.
	BenefitsOffered *bool `json:"benefitsOffered,omitempty"`
}

func (p *PazeCobrandItem) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PazeCobrandItem) GetBenefitsOffered() *bool {
	if p == nil {
		return nil
	}
	return p.BenefitsOffered
}
