// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ProductType string

const (
	ProductTypePhysical    ProductType = "physical"
	ProductTypeDiscount    ProductType = "discount"
	ProductTypeShippingFee ProductType = "shipping_fee"
	ProductTypeSalesTax    ProductType = "sales_tax"
	ProductTypeDigital     ProductType = "digital"
	ProductTypeGiftCard    ProductType = "gift_card"
	ProductTypeStoreCredit ProductType = "store_credit"
	ProductTypeSurcharge   ProductType = "surcharge"
)

func (e ProductType) ToPointer() *ProductType {
	return &e
}
