// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RefundTargetType string

const (
	RefundTargetTypePaymentMethod      RefundTargetType = "payment-method"
	RefundTargetTypeGiftCardRedemption RefundTargetType = "gift-card-redemption"
)

func (e RefundTargetType) ToPointer() *RefundTargetType {
	return &e
}
