// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// Settlements - A list of settlement records for a transaction.
type Settlements struct {
	// The list of settlement objects.
	Items []Settlement `json:"items"`
}

func (o *Settlements) GetItems() []Settlement {
	if o == nil {
		return []Settlement{}
	}
	return o.Items
}
