// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// StatementDescriptor - Information to show the user on their payments statement
type StatementDescriptor struct {
	// Reflects your doing business as (DBA) name.
	Name *string `json:"name,omitempty"`
	// A short description about the purchase.
	Description *string `json:"description,omitempty"`
	// The merchant's city to be displayed in a statement descriptor.
	City *string `json:"city,omitempty"`
	// The 2-letter ISO country code of the merchant to be displayed in a statement descriptor.
	Country *string `json:"country,omitempty"`
	// The value in the phone number field of a customer's statement which should be formatted according to the E164 number standard.
	PhoneNumber *string `json:"phone_number,omitempty"`
	// The merchant's URL to be displayed in a statement descriptor.
	URL *string `json:"url,omitempty"`
}

func (o *StatementDescriptor) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *StatementDescriptor) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *StatementDescriptor) GetCity() *string {
	if o == nil {
		return nil
	}
	return o.City
}

func (o *StatementDescriptor) GetCountry() *string {
	if o == nil {
		return nil
	}
	return o.Country
}

func (o *StatementDescriptor) GetPhoneNumber() *string {
	if o == nil {
		return nil
	}
	return o.PhoneNumber
}

func (o *StatementDescriptor) GetURL() *string {
	if o == nil {
		return nil
	}
	return o.URL
}
