// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/gr4vy/gr4vy-go/internal/utils"
	"github.com/gr4vy/gr4vy-go/types"
	"time"
)

type ThreeDSecureScenario struct {
	// Always `three-d-secure-scenario`.
	type_ *string `const:"three-d-secure-scenario" json:"type"`
	// Unique identifier for the 3DS scenario
	ID string `json:"id"`
	// ID of the associated merchant account
	MerchantAccountID string `json:"merchant_account_id"`
	// The date and time when this 3DS scenario was first created in our system.
	CreatedAt time.Time `json:"created_at"`
	// The date and time when this 3DS scenario was last updated in our system.
	UpdatedAt  time.Time                      `json:"updated_at"`
	Conditions ThreeDSecureScenarioConditions `json:"conditions"`
	Outcome    ThreeDSecureScenarioOutcome    `json:"outcome"`
}

func (t ThreeDSecureScenario) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *ThreeDSecureScenario) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *ThreeDSecureScenario) GetType() *string {
	return types.Pointer("three-d-secure-scenario")
}

func (t *ThreeDSecureScenario) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

func (t *ThreeDSecureScenario) GetMerchantAccountID() string {
	if t == nil {
		return ""
	}
	return t.MerchantAccountID
}

func (t *ThreeDSecureScenario) GetCreatedAt() time.Time {
	if t == nil {
		return time.Time{}
	}
	return t.CreatedAt
}

func (t *ThreeDSecureScenario) GetUpdatedAt() time.Time {
	if t == nil {
		return time.Time{}
	}
	return t.UpdatedAt
}

func (t *ThreeDSecureScenario) GetConditions() ThreeDSecureScenarioConditions {
	if t == nil {
		return ThreeDSecureScenarioConditions{}
	}
	return t.Conditions
}

func (t *ThreeDSecureScenario) GetOutcome() ThreeDSecureScenarioOutcome {
	if t == nil {
		return ThreeDSecureScenarioOutcome{}
	}
	return t.Outcome
}
