// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TransactionRefundCreate struct {
	// The amount to refund, in the smallest currency unit (e.g., cents). If omitted, a full refund will be requested.
	Amount     *int64            `json:"amount,omitempty"`
	TargetType *RefundTargetType `json:"target_type,omitempty"`
	// The optional ID of the instrument to refund for. This is only required when the `target_type` is set to `gift-card-redemption`.
	TargetID *string `json:"target_id,omitempty"`
	// An optional reason to attach extra context to the refund request.
	Reason *string `json:"reason,omitempty"`
	// An external identifier that can be used to match the refund against your own records.
	ExternalIdentifier *string `json:"external_identifier,omitempty"`
}

func (t *TransactionRefundCreate) GetAmount() *int64 {
	if t == nil {
		return nil
	}
	return t.Amount
}

func (t *TransactionRefundCreate) GetTargetType() *RefundTargetType {
	if t == nil {
		return nil
	}
	return t.TargetType
}

func (t *TransactionRefundCreate) GetTargetID() *string {
	if t == nil {
		return nil
	}
	return t.TargetID
}

func (t *TransactionRefundCreate) GetReason() *string {
	if t == nil {
		return nil
	}
	return t.Reason
}

func (t *TransactionRefundCreate) GetExternalIdentifier() *string {
	if t == nil {
		return nil
	}
	return t.ExternalIdentifier
}
