// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/gr4vy/gr4vy-go/internal/utils"
	"github.com/gr4vy/gr4vy-go/types"
)

type TransactionCancel struct {
	// Always `transaction-cancel`.
	type_  *string      `const:"transaction-cancel" json:"type"`
	Status CancelStatus `json:"status"`
	// The standardized error code set by Gr4vy.
	Code *string `json:"code"`
	// This is the response code received from the payment service. This can be set to any value and is not standardized across different payment services.
	RawResponseCode *string `json:"raw_response_code"`
	// This is the response description received from the payment service. This can be set to any value and is not standardized across different payment services.
	RawResponseDescription *string `json:"raw_response_description"`
	// A full transaction resource.
	Transaction Transaction `json:"transaction"`
}

func (t TransactionCancel) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TransactionCancel) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, []string{"status", "code", "raw_response_code", "raw_response_description", "transaction"}); err != nil {
		return err
	}
	return nil
}

func (o *TransactionCancel) GetType() *string {
	return types.String("transaction-cancel")
}

func (o *TransactionCancel) GetStatus() CancelStatus {
	if o == nil {
		return CancelStatus("")
	}
	return o.Status
}

func (o *TransactionCancel) GetCode() *string {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *TransactionCancel) GetRawResponseCode() *string {
	if o == nil {
		return nil
	}
	return o.RawResponseCode
}

func (o *TransactionCancel) GetRawResponseDescription() *string {
	if o == nil {
		return nil
	}
	return o.RawResponseDescription
}

func (o *TransactionCancel) GetTransaction() Transaction {
	if o == nil {
		return Transaction{}
	}
	return o.Transaction
}
