// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// TransactionPaymentSource - The way payment method information made it to this transaction.
type TransactionPaymentSource string

const (
	TransactionPaymentSourceEcommerce   TransactionPaymentSource = "ecommerce"
	TransactionPaymentSourceMoto        TransactionPaymentSource = "moto"
	TransactionPaymentSourceRecurring   TransactionPaymentSource = "recurring"
	TransactionPaymentSourceInstallment TransactionPaymentSource = "installment"
	TransactionPaymentSourceCardOnFile  TransactionPaymentSource = "card_on_file"
)

func (e TransactionPaymentSource) ToPointer() *TransactionPaymentSource {
	return &e
}
func (e *TransactionPaymentSource) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ecommerce":
		fallthrough
	case "moto":
		fallthrough
	case "recurring":
		fallthrough
	case "installment":
		fallthrough
	case "card_on_file":
		*e = TransactionPaymentSource(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TransactionPaymentSource: %v", v)
	}
}
