// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TravelhubOptions struct {
	// A list of `customData` to pass to the TravelHub API.
	CustomData []TravelHubCustomData `json:"customData,omitempty"`
}

func (o *TravelhubOptions) GetCustomData() []TravelHubCustomData {
	if o == nil {
		return nil
	}
	return o.CustomData
}
