// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type WpayPaytoSimulationOptions struct {
	// The simulation being requested. Please refer to the developer guide for a list of all available simulations.
	Simulate *string `json:"simulate,omitempty"`
	// The delay in seconds before the requested simulation is executed.
	Delay *int64 `json:"delay,omitempty"`
}

func (o *WpayPaytoSimulationOptions) GetSimulate() *string {
	if o == nil {
		return nil
	}
	return o.Simulate
}

func (o *WpayPaytoSimulationOptions) GetDelay() *int64 {
	if o == nil {
		return nil
	}
	return o.Delay
}
