// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/gr4vy/gr4vy-go/internal/utils"
	"github.com/gr4vy/gr4vy-go/models/components"
)

type Response403CreateGiftCardType string

const (
	Response403CreateGiftCardTypeError403          Response403CreateGiftCardType = "Error403"
	Response403CreateGiftCardTypeError403Forbidden Response403CreateGiftCardType = "Error403Forbidden"
	Response403CreateGiftCardTypeError403Active    Response403CreateGiftCardType = "Error403Active"
)

// Response403CreateGiftCard - The credentials were invalid or the caller did not have permission to act on the resource.
type Response403CreateGiftCard struct {
	Error403          *components.Error403          `queryParam:"inline"`
	Error403Forbidden *components.Error403Forbidden `queryParam:"inline"`
	Error403Active    *components.Error403Active    `queryParam:"inline"`

	Type Response403CreateGiftCardType

	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &Response403CreateGiftCard{}

func CreateResponse403CreateGiftCardError403(error403 components.Error403) Response403CreateGiftCard {
	typ := Response403CreateGiftCardTypeError403

	return Response403CreateGiftCard{
		Error403: &error403,
		Type:     typ,
	}
}

func CreateResponse403CreateGiftCardError403Forbidden(error403Forbidden components.Error403Forbidden) Response403CreateGiftCard {
	typ := Response403CreateGiftCardTypeError403Forbidden

	return Response403CreateGiftCard{
		Error403Forbidden: &error403Forbidden,
		Type:              typ,
	}
}

func CreateResponse403CreateGiftCardError403Active(error403Active components.Error403Active) Response403CreateGiftCard {
	typ := Response403CreateGiftCardTypeError403Active

	return Response403CreateGiftCard{
		Error403Active: &error403Active,
		Type:           typ,
	}
}

func (u *Response403CreateGiftCard) UnmarshalJSON(data []byte) error {

	var error403 components.Error403 = components.Error403{}
	if err := utils.UnmarshalJSON(data, &error403, "", true, true); err == nil {
		u.Error403 = &error403
		u.Type = Response403CreateGiftCardTypeError403
		return nil
	}

	var error403Forbidden components.Error403Forbidden = components.Error403Forbidden{}
	if err := utils.UnmarshalJSON(data, &error403Forbidden, "", true, true); err == nil {
		u.Error403Forbidden = &error403Forbidden
		u.Type = Response403CreateGiftCardTypeError403Forbidden
		return nil
	}

	var error403Active components.Error403Active = components.Error403Active{}
	if err := utils.UnmarshalJSON(data, &error403Active, "", true, true); err == nil {
		u.Error403Active = &error403Active
		u.Type = Response403CreateGiftCardTypeError403Active
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Response403CreateGiftCard", string(data))
}

func (u Response403CreateGiftCard) MarshalJSON() ([]byte, error) {
	if u.Error403 != nil {
		return utils.MarshalJSON(u.Error403, "", true)
	}

	if u.Error403Forbidden != nil {
		return utils.MarshalJSON(u.Error403Forbidden, "", true)
	}

	if u.Error403Active != nil {
		return utils.MarshalJSON(u.Error403Active, "", true)
	}

	return nil, errors.New("could not marshal union type Response403CreateGiftCard: all fields are null")
}

func (u Response403CreateGiftCard) Error() string {
	switch u.Type {
	case Response403CreateGiftCardTypeError403:
		data, _ := json.Marshal(u.Error403)
		return string(data)
	case Response403CreateGiftCardTypeError403Forbidden:
		data, _ := json.Marshal(u.Error403Forbidden)
		return string(data)
	case Response403CreateGiftCardTypeError403Active:
		data, _ := json.Marshal(u.Error403Active)
		return string(data)
	default:
		return "unknown error"
	}
}
