// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/gr4vy/gr4vy-go/models/components"
)

type Error429 struct {
	// Always `error`.
	Type *string `const:"error" json:"type"`
	// Always `too_many_requests`
	Code *string `default:"too_many_requests" json:"code"`
	// Always `429`.
	Status *int64 `default:"429" json:"status"`
	// A human readable message that provides more context to the error.
	Message *string `json:"message"`
	// A list of details that further ellaborate on the error.
	Details  []components.ErrorDetail `json:"details,omitempty"`
	HTTPMeta components.HTTPMetadata  `json:"-"`
}

var _ error = &Error429{}

func (e *Error429) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
