// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/gr4vy/gr4vy-go/internal/utils"
	"github.com/gr4vy/gr4vy-go/models/components"
)

type Response403ListPaymentOptionsType string

const (
	Response403ListPaymentOptionsTypeError403          Response403ListPaymentOptionsType = "Error403"
	Response403ListPaymentOptionsTypeError403Forbidden Response403ListPaymentOptionsType = "Error403Forbidden"
	Response403ListPaymentOptionsTypeError403Active    Response403ListPaymentOptionsType = "Error403Active"
)

// Response403ListPaymentOptions - The credentials were invalid or the caller did not have permission to act on the resource.
type Response403ListPaymentOptions struct {
	Error403          *components.Error403          `queryParam:"inline"`
	Error403Forbidden *components.Error403Forbidden `queryParam:"inline"`
	Error403Active    *components.Error403Active    `queryParam:"inline"`

	Type Response403ListPaymentOptionsType

	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &Response403ListPaymentOptions{}

func CreateResponse403ListPaymentOptionsError403(error403 components.Error403) Response403ListPaymentOptions {
	typ := Response403ListPaymentOptionsTypeError403

	return Response403ListPaymentOptions{
		Error403: &error403,
		Type:     typ,
	}
}

func CreateResponse403ListPaymentOptionsError403Forbidden(error403Forbidden components.Error403Forbidden) Response403ListPaymentOptions {
	typ := Response403ListPaymentOptionsTypeError403Forbidden

	return Response403ListPaymentOptions{
		Error403Forbidden: &error403Forbidden,
		Type:              typ,
	}
}

func CreateResponse403ListPaymentOptionsError403Active(error403Active components.Error403Active) Response403ListPaymentOptions {
	typ := Response403ListPaymentOptionsTypeError403Active

	return Response403ListPaymentOptions{
		Error403Active: &error403Active,
		Type:           typ,
	}
}

func (u *Response403ListPaymentOptions) UnmarshalJSON(data []byte) error {

	var error403 components.Error403 = components.Error403{}
	if err := utils.UnmarshalJSON(data, &error403, "", true, true); err == nil {
		u.Error403 = &error403
		u.Type = Response403ListPaymentOptionsTypeError403
		return nil
	}

	var error403Forbidden components.Error403Forbidden = components.Error403Forbidden{}
	if err := utils.UnmarshalJSON(data, &error403Forbidden, "", true, true); err == nil {
		u.Error403Forbidden = &error403Forbidden
		u.Type = Response403ListPaymentOptionsTypeError403Forbidden
		return nil
	}

	var error403Active components.Error403Active = components.Error403Active{}
	if err := utils.UnmarshalJSON(data, &error403Active, "", true, true); err == nil {
		u.Error403Active = &error403Active
		u.Type = Response403ListPaymentOptionsTypeError403Active
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Response403ListPaymentOptions", string(data))
}

func (u Response403ListPaymentOptions) MarshalJSON() ([]byte, error) {
	if u.Error403 != nil {
		return utils.MarshalJSON(u.Error403, "", true)
	}

	if u.Error403Forbidden != nil {
		return utils.MarshalJSON(u.Error403Forbidden, "", true)
	}

	if u.Error403Active != nil {
		return utils.MarshalJSON(u.Error403Active, "", true)
	}

	return nil, errors.New("could not marshal union type Response403ListPaymentOptions: all fields are null")
}

func (u Response403ListPaymentOptions) Error() string {
	switch u.Type {
	case Response403ListPaymentOptionsTypeError403:
		data, _ := json.Marshal(u.Error403)
		return string(data)
	case Response403ListPaymentOptionsTypeError403Forbidden:
		data, _ := json.Marshal(u.Error403Forbidden)
		return string(data)
	case Response403ListPaymentOptionsTypeError403Active:
		data, _ := json.Marshal(u.Error403Active)
		return string(data)
	default:
		return "unknown error"
	}
}
