workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    openapi:
        inputs:
            - location: https://gr4vy.github.io/gr4vy-openapi/core/openapi.json
        overlays:
            - location: ./.speakeasy/overlays/servers.yaml
            - location: ./.speakeasy/overlays/security.yaml
            - location: ./.speakeasy/overlays/enums.yaml
            - location: ./.speakeasy/overlays/retries.yaml
            - location: ./.speakeasy/overlays/mid-global.yaml
            - location: ./.speakeasy/overlays/fix-base-model.yaml
            - location: ./.speakeasy/overlays/fix-checkout-session-body.yaml
            - location: ./.speakeasy/overlays/fix-remove-unwanted-headers.yaml
            - location: ./.speakeasy/overlays/fix-add-x-forwarded-for-header.yaml
        registry:
            location: registry.speakeasyapi.dev/gr4vy/gr4vy/openapi
targets:
    go:
        target: go
        source: openapi
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/gr4vy/gr4vy/openapi-go-code-samples
            labelOverride:
                fixedValue: Go
            blocking: false
