/*
 * Gr4vy API
 *
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * API version: 1.1.0-beta
 * Contact: code@gr4vy.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package Openapi

import (
	"encoding/json"
)

// ConnectionOptionsFiservCardInstallmentOptions Fiserv installment options.
type ConnectionOptionsFiservCardInstallmentOptions struct {
	// Number of installments for a sale transaction if the customer pays the total amount in multiple transactions.
	NumberOfInstallments NullableFloat32 `json:"numberOfInstallments,omitempty"`
	// Indicates whether the installment interest amount has been applied.
	InstallmentsInterest NullableBool `json:"installmentsInterest,omitempty"`
	// The number of months the first installment payment will be delayed.
	InstallmentDelayMonths NullableFloat32 `json:"installmentDelayMonths,omitempty"`
	// Indicates if the merchant supports merchant advice code (MAC) in order to receive table 55 code for a declined recurring transaction.
	MerchantAdviceCodeSupported NullableBool `json:"merchantAdviceCodeSupported,omitempty"`
}

// NewConnectionOptionsFiservCardInstallmentOptions instantiates a new ConnectionOptionsFiservCardInstallmentOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectionOptionsFiservCardInstallmentOptions() *ConnectionOptionsFiservCardInstallmentOptions {
	this := ConnectionOptionsFiservCardInstallmentOptions{}
	return &this
}

// NewConnectionOptionsFiservCardInstallmentOptionsWithDefaults instantiates a new ConnectionOptionsFiservCardInstallmentOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectionOptionsFiservCardInstallmentOptionsWithDefaults() *ConnectionOptionsFiservCardInstallmentOptions {
	this := ConnectionOptionsFiservCardInstallmentOptions{}
	return &this
}

// GetNumberOfInstallments returns the NumberOfInstallments field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConnectionOptionsFiservCardInstallmentOptions) GetNumberOfInstallments() float32 {
	if o == nil || o.NumberOfInstallments.Get() == nil {
		var ret float32
		return ret
	}
	return *o.NumberOfInstallments.Get()
}

// GetNumberOfInstallmentsOk returns a tuple with the NumberOfInstallments field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConnectionOptionsFiservCardInstallmentOptions) GetNumberOfInstallmentsOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return o.NumberOfInstallments.Get(), o.NumberOfInstallments.IsSet()
}

// HasNumberOfInstallments returns a boolean if a field has been set.
func (o *ConnectionOptionsFiservCardInstallmentOptions) HasNumberOfInstallments() bool {
	if o != nil && o.NumberOfInstallments.IsSet() {
		return true
	}

	return false
}

// SetNumberOfInstallments gets a reference to the given NullableFloat32 and assigns it to the NumberOfInstallments field.
func (o *ConnectionOptionsFiservCardInstallmentOptions) SetNumberOfInstallments(v float32) {
	o.NumberOfInstallments.Set(&v)
}
// SetNumberOfInstallmentsNil sets the value for NumberOfInstallments to be an explicit nil
func (o *ConnectionOptionsFiservCardInstallmentOptions) SetNumberOfInstallmentsNil() {
	o.NumberOfInstallments.Set(nil)
}

// UnsetNumberOfInstallments ensures that no value is present for NumberOfInstallments, not even an explicit nil
func (o *ConnectionOptionsFiservCardInstallmentOptions) UnsetNumberOfInstallments() {
	o.NumberOfInstallments.Unset()
}

// GetInstallmentsInterest returns the InstallmentsInterest field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConnectionOptionsFiservCardInstallmentOptions) GetInstallmentsInterest() bool {
	if o == nil || o.InstallmentsInterest.Get() == nil {
		var ret bool
		return ret
	}
	return *o.InstallmentsInterest.Get()
}

// GetInstallmentsInterestOk returns a tuple with the InstallmentsInterest field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConnectionOptionsFiservCardInstallmentOptions) GetInstallmentsInterestOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return o.InstallmentsInterest.Get(), o.InstallmentsInterest.IsSet()
}

// HasInstallmentsInterest returns a boolean if a field has been set.
func (o *ConnectionOptionsFiservCardInstallmentOptions) HasInstallmentsInterest() bool {
	if o != nil && o.InstallmentsInterest.IsSet() {
		return true
	}

	return false
}

// SetInstallmentsInterest gets a reference to the given NullableBool and assigns it to the InstallmentsInterest field.
func (o *ConnectionOptionsFiservCardInstallmentOptions) SetInstallmentsInterest(v bool) {
	o.InstallmentsInterest.Set(&v)
}
// SetInstallmentsInterestNil sets the value for InstallmentsInterest to be an explicit nil
func (o *ConnectionOptionsFiservCardInstallmentOptions) SetInstallmentsInterestNil() {
	o.InstallmentsInterest.Set(nil)
}

// UnsetInstallmentsInterest ensures that no value is present for InstallmentsInterest, not even an explicit nil
func (o *ConnectionOptionsFiservCardInstallmentOptions) UnsetInstallmentsInterest() {
	o.InstallmentsInterest.Unset()
}

// GetInstallmentDelayMonths returns the InstallmentDelayMonths field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConnectionOptionsFiservCardInstallmentOptions) GetInstallmentDelayMonths() float32 {
	if o == nil || o.InstallmentDelayMonths.Get() == nil {
		var ret float32
		return ret
	}
	return *o.InstallmentDelayMonths.Get()
}

// GetInstallmentDelayMonthsOk returns a tuple with the InstallmentDelayMonths field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConnectionOptionsFiservCardInstallmentOptions) GetInstallmentDelayMonthsOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return o.InstallmentDelayMonths.Get(), o.InstallmentDelayMonths.IsSet()
}

// HasInstallmentDelayMonths returns a boolean if a field has been set.
func (o *ConnectionOptionsFiservCardInstallmentOptions) HasInstallmentDelayMonths() bool {
	if o != nil && o.InstallmentDelayMonths.IsSet() {
		return true
	}

	return false
}

// SetInstallmentDelayMonths gets a reference to the given NullableFloat32 and assigns it to the InstallmentDelayMonths field.
func (o *ConnectionOptionsFiservCardInstallmentOptions) SetInstallmentDelayMonths(v float32) {
	o.InstallmentDelayMonths.Set(&v)
}
// SetInstallmentDelayMonthsNil sets the value for InstallmentDelayMonths to be an explicit nil
func (o *ConnectionOptionsFiservCardInstallmentOptions) SetInstallmentDelayMonthsNil() {
	o.InstallmentDelayMonths.Set(nil)
}

// UnsetInstallmentDelayMonths ensures that no value is present for InstallmentDelayMonths, not even an explicit nil
func (o *ConnectionOptionsFiservCardInstallmentOptions) UnsetInstallmentDelayMonths() {
	o.InstallmentDelayMonths.Unset()
}

// GetMerchantAdviceCodeSupported returns the MerchantAdviceCodeSupported field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConnectionOptionsFiservCardInstallmentOptions) GetMerchantAdviceCodeSupported() bool {
	if o == nil || o.MerchantAdviceCodeSupported.Get() == nil {
		var ret bool
		return ret
	}
	return *o.MerchantAdviceCodeSupported.Get()
}

// GetMerchantAdviceCodeSupportedOk returns a tuple with the MerchantAdviceCodeSupported field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConnectionOptionsFiservCardInstallmentOptions) GetMerchantAdviceCodeSupportedOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return o.MerchantAdviceCodeSupported.Get(), o.MerchantAdviceCodeSupported.IsSet()
}

// HasMerchantAdviceCodeSupported returns a boolean if a field has been set.
func (o *ConnectionOptionsFiservCardInstallmentOptions) HasMerchantAdviceCodeSupported() bool {
	if o != nil && o.MerchantAdviceCodeSupported.IsSet() {
		return true
	}

	return false
}

// SetMerchantAdviceCodeSupported gets a reference to the given NullableBool and assigns it to the MerchantAdviceCodeSupported field.
func (o *ConnectionOptionsFiservCardInstallmentOptions) SetMerchantAdviceCodeSupported(v bool) {
	o.MerchantAdviceCodeSupported.Set(&v)
}
// SetMerchantAdviceCodeSupportedNil sets the value for MerchantAdviceCodeSupported to be an explicit nil
func (o *ConnectionOptionsFiservCardInstallmentOptions) SetMerchantAdviceCodeSupportedNil() {
	o.MerchantAdviceCodeSupported.Set(nil)
}

// UnsetMerchantAdviceCodeSupported ensures that no value is present for MerchantAdviceCodeSupported, not even an explicit nil
func (o *ConnectionOptionsFiservCardInstallmentOptions) UnsetMerchantAdviceCodeSupported() {
	o.MerchantAdviceCodeSupported.Unset()
}

func (o ConnectionOptionsFiservCardInstallmentOptions) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.NumberOfInstallments.IsSet() {
		toSerialize["numberOfInstallments"] = o.NumberOfInstallments.Get()
	}
	if o.InstallmentsInterest.IsSet() {
		toSerialize["installmentsInterest"] = o.InstallmentsInterest.Get()
	}
	if o.InstallmentDelayMonths.IsSet() {
		toSerialize["installmentDelayMonths"] = o.InstallmentDelayMonths.Get()
	}
	if o.MerchantAdviceCodeSupported.IsSet() {
		toSerialize["merchantAdviceCodeSupported"] = o.MerchantAdviceCodeSupported.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableConnectionOptionsFiservCardInstallmentOptions struct {
	value *ConnectionOptionsFiservCardInstallmentOptions
	isSet bool
}

func (v NullableConnectionOptionsFiservCardInstallmentOptions) Get() *ConnectionOptionsFiservCardInstallmentOptions {
	return v.value
}

func (v *NullableConnectionOptionsFiservCardInstallmentOptions) Set(val *ConnectionOptionsFiservCardInstallmentOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectionOptionsFiservCardInstallmentOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectionOptionsFiservCardInstallmentOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectionOptionsFiservCardInstallmentOptions(val *ConnectionOptionsFiservCardInstallmentOptions) *NullableConnectionOptionsFiservCardInstallmentOptions {
	return &NullableConnectionOptionsFiservCardInstallmentOptions{value: val, isSet: true}
}

func (v NullableConnectionOptionsFiservCardInstallmentOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectionOptionsFiservCardInstallmentOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


