/*
 * Gr4vy API (Beta)
 *
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * API version: 1.0
 * Contact: code@gr4vy.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package Openapi

import (
	"encoding/json"
)

// CardRuleTextCondition Part of a rule that matches text fields. It defines the condition under which this rule applies.
type CardRuleTextCondition struct {
	// `text`.
	Match string `json:"match"`
	// The transaction field to filter by.
	Key string `json:"key"`
	// The comparison to make to `value` property.
	Operator string `json:"operator"`
	// The values to compare the `key` to.
	Value []string `json:"value"`
}

// NewCardRuleTextCondition instantiates a new CardRuleTextCondition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCardRuleTextCondition(match string, key string, operator string, value []string) *CardRuleTextCondition {
	this := CardRuleTextCondition{}
	this.Match = match
	this.Key = key
	this.Operator = operator
	this.Value = value
	return &this
}

// NewCardRuleTextConditionWithDefaults instantiates a new CardRuleTextCondition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCardRuleTextConditionWithDefaults() *CardRuleTextCondition {
	this := CardRuleTextCondition{}
	return &this
}

// GetMatch returns the Match field value
func (o *CardRuleTextCondition) GetMatch() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Match
}

// GetMatchOk returns a tuple with the Match field value
// and a boolean to check if the value has been set.
func (o *CardRuleTextCondition) GetMatchOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Match, true
}

// SetMatch sets field value
func (o *CardRuleTextCondition) SetMatch(v string) {
	o.Match = v
}

// GetKey returns the Key field value
func (o *CardRuleTextCondition) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *CardRuleTextCondition) GetKeyOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *CardRuleTextCondition) SetKey(v string) {
	o.Key = v
}

// GetOperator returns the Operator field value
func (o *CardRuleTextCondition) GetOperator() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Operator
}

// GetOperatorOk returns a tuple with the Operator field value
// and a boolean to check if the value has been set.
func (o *CardRuleTextCondition) GetOperatorOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Operator, true
}

// SetOperator sets field value
func (o *CardRuleTextCondition) SetOperator(v string) {
	o.Operator = v
}

// GetValue returns the Value field value
func (o *CardRuleTextCondition) GetValue() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *CardRuleTextCondition) GetValueOk() (*[]string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *CardRuleTextCondition) SetValue(v []string) {
	o.Value = v
}

func (o CardRuleTextCondition) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["match"] = o.Match
	}
	if true {
		toSerialize["key"] = o.Key
	}
	if true {
		toSerialize["operator"] = o.Operator
	}
	if true {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableCardRuleTextCondition struct {
	value *CardRuleTextCondition
	isSet bool
}

func (v NullableCardRuleTextCondition) Get() *CardRuleTextCondition {
	return v.value
}

func (v *NullableCardRuleTextCondition) Set(val *CardRuleTextCondition) {
	v.value = val
	v.isSet = true
}

func (v NullableCardRuleTextCondition) IsSet() bool {
	return v.isSet
}

func (v *NullableCardRuleTextCondition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCardRuleTextCondition(val *CardRuleTextCondition) *NullableCardRuleTextCondition {
	return &NullableCardRuleTextCondition{value: val, isSet: true}
}

func (v NullableCardRuleTextCondition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCardRuleTextCondition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


