/*
 * Gr4vy API
 *
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * API version: 1.1.0-beta
 * Contact: code@gr4vy.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package Openapi

import (
	"encoding/json"
)

// GiftCardServiceFields struct for GiftCardServiceFields
type GiftCardServiceFields struct {
	// The key of the field.
	Key *string `json:"key,omitempty"`
	// The value of the field.
	Value *string `json:"value,omitempty"`
}

// NewGiftCardServiceFields instantiates a new GiftCardServiceFields object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGiftCardServiceFields() *GiftCardServiceFields {
	this := GiftCardServiceFields{}
	return &this
}

// NewGiftCardServiceFieldsWithDefaults instantiates a new GiftCardServiceFields object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGiftCardServiceFieldsWithDefaults() *GiftCardServiceFields {
	this := GiftCardServiceFields{}
	return &this
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *GiftCardServiceFields) GetKey() string {
	if o == nil || o.Key == nil {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GiftCardServiceFields) GetKeyOk() (*string, bool) {
	if o == nil || o.Key == nil {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *GiftCardServiceFields) HasKey() bool {
	if o != nil && o.Key != nil {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *GiftCardServiceFields) SetKey(v string) {
	o.Key = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *GiftCardServiceFields) GetValue() string {
	if o == nil || o.Value == nil {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GiftCardServiceFields) GetValueOk() (*string, bool) {
	if o == nil || o.Value == nil {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *GiftCardServiceFields) HasValue() bool {
	if o != nil && o.Value != nil {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *GiftCardServiceFields) SetValue(v string) {
	o.Value = &v
}

func (o GiftCardServiceFields) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Key != nil {
		toSerialize["key"] = o.Key
	}
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableGiftCardServiceFields struct {
	value *GiftCardServiceFields
	isSet bool
}

func (v NullableGiftCardServiceFields) Get() *GiftCardServiceFields {
	return v.value
}

func (v *NullableGiftCardServiceFields) Set(val *GiftCardServiceFields) {
	v.value = val
	v.isSet = true
}

func (v NullableGiftCardServiceFields) IsSet() bool {
	return v.isSet
}

func (v *NullableGiftCardServiceFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGiftCardServiceFields(val *GiftCardServiceFields) *NullableGiftCardServiceFields {
	return &NullableGiftCardServiceFields{value: val, isSet: true}
}

func (v NullableGiftCardServiceFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGiftCardServiceFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


