/*
 * Gr4vy API
 *
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * API version: 1.1.0-beta
 * Contact: code@gr4vy.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package Openapi

import (
	"encoding/json"
	"time"
)

// MerchantProfileSchemeSummary Merchant profile for a specific scheme.
type MerchantProfileSchemeSummary struct {
	// Acquirer bin to use when calling 3DS through this scheme.
	MerchantAcquirerBin *string `json:"merchant_acquirer_bin,omitempty"`
	// URL to send when calling 3DS through this scheme.
	MerchantUrl *string `json:"merchant_url,omitempty"`
	// Merchant ID to use when calling 3DS through this scheme.
	MerchantAcquirerId *string `json:"merchant_acquirer_id,omitempty"`
	// Merchant name to use when calling 3DS through this scheme.
	MerchantName *string `json:"merchant_name,omitempty"`
	// Merchant country code to use when calling 3DS through this scheme.
	MerchantCountryCode *string `json:"merchant_country_code,omitempty"`
	// Merchant category code to use when calling 3DS through this scheme.
	MerchantCategoryCode *string `json:"merchant_category_code,omitempty"`
	// The date and time when this profile was created.
	CreatedAt *time.Time `json:"created_at,omitempty"`
}

// NewMerchantProfileSchemeSummary instantiates a new MerchantProfileSchemeSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMerchantProfileSchemeSummary() *MerchantProfileSchemeSummary {
	this := MerchantProfileSchemeSummary{}
	return &this
}

// NewMerchantProfileSchemeSummaryWithDefaults instantiates a new MerchantProfileSchemeSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMerchantProfileSchemeSummaryWithDefaults() *MerchantProfileSchemeSummary {
	this := MerchantProfileSchemeSummary{}
	return &this
}

// GetMerchantAcquirerBin returns the MerchantAcquirerBin field value if set, zero value otherwise.
func (o *MerchantProfileSchemeSummary) GetMerchantAcquirerBin() string {
	if o == nil || o.MerchantAcquirerBin == nil {
		var ret string
		return ret
	}
	return *o.MerchantAcquirerBin
}

// GetMerchantAcquirerBinOk returns a tuple with the MerchantAcquirerBin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantProfileSchemeSummary) GetMerchantAcquirerBinOk() (*string, bool) {
	if o == nil || o.MerchantAcquirerBin == nil {
		return nil, false
	}
	return o.MerchantAcquirerBin, true
}

// HasMerchantAcquirerBin returns a boolean if a field has been set.
func (o *MerchantProfileSchemeSummary) HasMerchantAcquirerBin() bool {
	if o != nil && o.MerchantAcquirerBin != nil {
		return true
	}

	return false
}

// SetMerchantAcquirerBin gets a reference to the given string and assigns it to the MerchantAcquirerBin field.
func (o *MerchantProfileSchemeSummary) SetMerchantAcquirerBin(v string) {
	o.MerchantAcquirerBin = &v
}

// GetMerchantUrl returns the MerchantUrl field value if set, zero value otherwise.
func (o *MerchantProfileSchemeSummary) GetMerchantUrl() string {
	if o == nil || o.MerchantUrl == nil {
		var ret string
		return ret
	}
	return *o.MerchantUrl
}

// GetMerchantUrlOk returns a tuple with the MerchantUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantProfileSchemeSummary) GetMerchantUrlOk() (*string, bool) {
	if o == nil || o.MerchantUrl == nil {
		return nil, false
	}
	return o.MerchantUrl, true
}

// HasMerchantUrl returns a boolean if a field has been set.
func (o *MerchantProfileSchemeSummary) HasMerchantUrl() bool {
	if o != nil && o.MerchantUrl != nil {
		return true
	}

	return false
}

// SetMerchantUrl gets a reference to the given string and assigns it to the MerchantUrl field.
func (o *MerchantProfileSchemeSummary) SetMerchantUrl(v string) {
	o.MerchantUrl = &v
}

// GetMerchantAcquirerId returns the MerchantAcquirerId field value if set, zero value otherwise.
func (o *MerchantProfileSchemeSummary) GetMerchantAcquirerId() string {
	if o == nil || o.MerchantAcquirerId == nil {
		var ret string
		return ret
	}
	return *o.MerchantAcquirerId
}

// GetMerchantAcquirerIdOk returns a tuple with the MerchantAcquirerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantProfileSchemeSummary) GetMerchantAcquirerIdOk() (*string, bool) {
	if o == nil || o.MerchantAcquirerId == nil {
		return nil, false
	}
	return o.MerchantAcquirerId, true
}

// HasMerchantAcquirerId returns a boolean if a field has been set.
func (o *MerchantProfileSchemeSummary) HasMerchantAcquirerId() bool {
	if o != nil && o.MerchantAcquirerId != nil {
		return true
	}

	return false
}

// SetMerchantAcquirerId gets a reference to the given string and assigns it to the MerchantAcquirerId field.
func (o *MerchantProfileSchemeSummary) SetMerchantAcquirerId(v string) {
	o.MerchantAcquirerId = &v
}

// GetMerchantName returns the MerchantName field value if set, zero value otherwise.
func (o *MerchantProfileSchemeSummary) GetMerchantName() string {
	if o == nil || o.MerchantName == nil {
		var ret string
		return ret
	}
	return *o.MerchantName
}

// GetMerchantNameOk returns a tuple with the MerchantName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantProfileSchemeSummary) GetMerchantNameOk() (*string, bool) {
	if o == nil || o.MerchantName == nil {
		return nil, false
	}
	return o.MerchantName, true
}

// HasMerchantName returns a boolean if a field has been set.
func (o *MerchantProfileSchemeSummary) HasMerchantName() bool {
	if o != nil && o.MerchantName != nil {
		return true
	}

	return false
}

// SetMerchantName gets a reference to the given string and assigns it to the MerchantName field.
func (o *MerchantProfileSchemeSummary) SetMerchantName(v string) {
	o.MerchantName = &v
}

// GetMerchantCountryCode returns the MerchantCountryCode field value if set, zero value otherwise.
func (o *MerchantProfileSchemeSummary) GetMerchantCountryCode() string {
	if o == nil || o.MerchantCountryCode == nil {
		var ret string
		return ret
	}
	return *o.MerchantCountryCode
}

// GetMerchantCountryCodeOk returns a tuple with the MerchantCountryCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantProfileSchemeSummary) GetMerchantCountryCodeOk() (*string, bool) {
	if o == nil || o.MerchantCountryCode == nil {
		return nil, false
	}
	return o.MerchantCountryCode, true
}

// HasMerchantCountryCode returns a boolean if a field has been set.
func (o *MerchantProfileSchemeSummary) HasMerchantCountryCode() bool {
	if o != nil && o.MerchantCountryCode != nil {
		return true
	}

	return false
}

// SetMerchantCountryCode gets a reference to the given string and assigns it to the MerchantCountryCode field.
func (o *MerchantProfileSchemeSummary) SetMerchantCountryCode(v string) {
	o.MerchantCountryCode = &v
}

// GetMerchantCategoryCode returns the MerchantCategoryCode field value if set, zero value otherwise.
func (o *MerchantProfileSchemeSummary) GetMerchantCategoryCode() string {
	if o == nil || o.MerchantCategoryCode == nil {
		var ret string
		return ret
	}
	return *o.MerchantCategoryCode
}

// GetMerchantCategoryCodeOk returns a tuple with the MerchantCategoryCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantProfileSchemeSummary) GetMerchantCategoryCodeOk() (*string, bool) {
	if o == nil || o.MerchantCategoryCode == nil {
		return nil, false
	}
	return o.MerchantCategoryCode, true
}

// HasMerchantCategoryCode returns a boolean if a field has been set.
func (o *MerchantProfileSchemeSummary) HasMerchantCategoryCode() bool {
	if o != nil && o.MerchantCategoryCode != nil {
		return true
	}

	return false
}

// SetMerchantCategoryCode gets a reference to the given string and assigns it to the MerchantCategoryCode field.
func (o *MerchantProfileSchemeSummary) SetMerchantCategoryCode(v string) {
	o.MerchantCategoryCode = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *MerchantProfileSchemeSummary) GetCreatedAt() time.Time {
	if o == nil || o.CreatedAt == nil {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantProfileSchemeSummary) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || o.CreatedAt == nil {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *MerchantProfileSchemeSummary) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *MerchantProfileSchemeSummary) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

func (o MerchantProfileSchemeSummary) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.MerchantAcquirerBin != nil {
		toSerialize["merchant_acquirer_bin"] = o.MerchantAcquirerBin
	}
	if o.MerchantUrl != nil {
		toSerialize["merchant_url"] = o.MerchantUrl
	}
	if o.MerchantAcquirerId != nil {
		toSerialize["merchant_acquirer_id"] = o.MerchantAcquirerId
	}
	if o.MerchantName != nil {
		toSerialize["merchant_name"] = o.MerchantName
	}
	if o.MerchantCountryCode != nil {
		toSerialize["merchant_country_code"] = o.MerchantCountryCode
	}
	if o.MerchantCategoryCode != nil {
		toSerialize["merchant_category_code"] = o.MerchantCategoryCode
	}
	if o.CreatedAt != nil {
		toSerialize["created_at"] = o.CreatedAt
	}
	return json.Marshal(toSerialize)
}

type NullableMerchantProfileSchemeSummary struct {
	value *MerchantProfileSchemeSummary
	isSet bool
}

func (v NullableMerchantProfileSchemeSummary) Get() *MerchantProfileSchemeSummary {
	return v.value
}

func (v *NullableMerchantProfileSchemeSummary) Set(val *MerchantProfileSchemeSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableMerchantProfileSchemeSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableMerchantProfileSchemeSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMerchantProfileSchemeSummary(val *MerchantProfileSchemeSummary) *NullableMerchantProfileSchemeSummary {
	return &NullableMerchantProfileSchemeSummary{value: val, isSet: true}
}

func (v NullableMerchantProfileSchemeSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMerchantProfileSchemeSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


