/*
 * Gr4vy API
 *
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * API version: 1.1.0-beta
 * Contact: code@gr4vy.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package Openapi

import (
	"encoding/json"
)

// CardRequest Details to register a new card payment method.
type CardRequest struct {
	// `card`.
	Method string `json:"method"`
	// The 13-19 digit number for this card as it can be found on the front of the card.
	Number string `json:"number"`
	// The expiration date of the card, formatted `MM/YY`.
	ExpirationDate string `json:"expiration_date"`
	// The 3 or 4 digit security code often found on the card. This often referred to as the CVV or CVD.  The security code can only be set if the stored payment method represents a card.
	SecurityCode NullableString `json:"security_code,omitempty"`
	// An external identifier that can be used to match the card against your own records.
	ExternalIdentifier NullableString `json:"external_identifier,omitempty"`
	// The ID of the buyer to associate this payment method to. If this field is provided then the `buyer_external_identifier` field needs to be unset.
	BuyerId *string `json:"buyer_id,omitempty"`
	// The `external_identifier` of the buyer to associate this payment method to. If this field is provided then the `buyer_id` field needs to be unset.
	BuyerExternalIdentifier *string `json:"buyer_external_identifier,omitempty"`
	// The redirect URL to redirect a buyer to after they have authorized their transaction or payment method. This only applies to payment methods that require buyer approval.
	RedirectUrl NullableString `json:"redirect_url,omitempty"`
}

// NewCardRequest instantiates a new CardRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCardRequest(method string, number string, expirationDate string) *CardRequest {
	this := CardRequest{}
	this.Method = method
	this.Number = number
	this.ExpirationDate = expirationDate
	return &this
}

// NewCardRequestWithDefaults instantiates a new CardRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCardRequestWithDefaults() *CardRequest {
	this := CardRequest{}
	return &this
}

// GetMethod returns the Method field value
func (o *CardRequest) GetMethod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Method
}

// GetMethodOk returns a tuple with the Method field value
// and a boolean to check if the value has been set.
func (o *CardRequest) GetMethodOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Method, true
}

// SetMethod sets field value
func (o *CardRequest) SetMethod(v string) {
	o.Method = v
}

// GetNumber returns the Number field value
func (o *CardRequest) GetNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Number
}

// GetNumberOk returns a tuple with the Number field value
// and a boolean to check if the value has been set.
func (o *CardRequest) GetNumberOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Number, true
}

// SetNumber sets field value
func (o *CardRequest) SetNumber(v string) {
	o.Number = v
}

// GetExpirationDate returns the ExpirationDate field value
func (o *CardRequest) GetExpirationDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExpirationDate
}

// GetExpirationDateOk returns a tuple with the ExpirationDate field value
// and a boolean to check if the value has been set.
func (o *CardRequest) GetExpirationDateOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ExpirationDate, true
}

// SetExpirationDate sets field value
func (o *CardRequest) SetExpirationDate(v string) {
	o.ExpirationDate = v
}

// GetSecurityCode returns the SecurityCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CardRequest) GetSecurityCode() string {
	if o == nil || o.SecurityCode.Get() == nil {
		var ret string
		return ret
	}
	return *o.SecurityCode.Get()
}

// GetSecurityCodeOk returns a tuple with the SecurityCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CardRequest) GetSecurityCodeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.SecurityCode.Get(), o.SecurityCode.IsSet()
}

// HasSecurityCode returns a boolean if a field has been set.
func (o *CardRequest) HasSecurityCode() bool {
	if o != nil && o.SecurityCode.IsSet() {
		return true
	}

	return false
}

// SetSecurityCode gets a reference to the given NullableString and assigns it to the SecurityCode field.
func (o *CardRequest) SetSecurityCode(v string) {
	o.SecurityCode.Set(&v)
}
// SetSecurityCodeNil sets the value for SecurityCode to be an explicit nil
func (o *CardRequest) SetSecurityCodeNil() {
	o.SecurityCode.Set(nil)
}

// UnsetSecurityCode ensures that no value is present for SecurityCode, not even an explicit nil
func (o *CardRequest) UnsetSecurityCode() {
	o.SecurityCode.Unset()
}

// GetExternalIdentifier returns the ExternalIdentifier field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CardRequest) GetExternalIdentifier() string {
	if o == nil || o.ExternalIdentifier.Get() == nil {
		var ret string
		return ret
	}
	return *o.ExternalIdentifier.Get()
}

// GetExternalIdentifierOk returns a tuple with the ExternalIdentifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CardRequest) GetExternalIdentifierOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.ExternalIdentifier.Get(), o.ExternalIdentifier.IsSet()
}

// HasExternalIdentifier returns a boolean if a field has been set.
func (o *CardRequest) HasExternalIdentifier() bool {
	if o != nil && o.ExternalIdentifier.IsSet() {
		return true
	}

	return false
}

// SetExternalIdentifier gets a reference to the given NullableString and assigns it to the ExternalIdentifier field.
func (o *CardRequest) SetExternalIdentifier(v string) {
	o.ExternalIdentifier.Set(&v)
}
// SetExternalIdentifierNil sets the value for ExternalIdentifier to be an explicit nil
func (o *CardRequest) SetExternalIdentifierNil() {
	o.ExternalIdentifier.Set(nil)
}

// UnsetExternalIdentifier ensures that no value is present for ExternalIdentifier, not even an explicit nil
func (o *CardRequest) UnsetExternalIdentifier() {
	o.ExternalIdentifier.Unset()
}

// GetBuyerId returns the BuyerId field value if set, zero value otherwise.
func (o *CardRequest) GetBuyerId() string {
	if o == nil || o.BuyerId == nil {
		var ret string
		return ret
	}
	return *o.BuyerId
}

// GetBuyerIdOk returns a tuple with the BuyerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardRequest) GetBuyerIdOk() (*string, bool) {
	if o == nil || o.BuyerId == nil {
		return nil, false
	}
	return o.BuyerId, true
}

// HasBuyerId returns a boolean if a field has been set.
func (o *CardRequest) HasBuyerId() bool {
	if o != nil && o.BuyerId != nil {
		return true
	}

	return false
}

// SetBuyerId gets a reference to the given string and assigns it to the BuyerId field.
func (o *CardRequest) SetBuyerId(v string) {
	o.BuyerId = &v
}

// GetBuyerExternalIdentifier returns the BuyerExternalIdentifier field value if set, zero value otherwise.
func (o *CardRequest) GetBuyerExternalIdentifier() string {
	if o == nil || o.BuyerExternalIdentifier == nil {
		var ret string
		return ret
	}
	return *o.BuyerExternalIdentifier
}

// GetBuyerExternalIdentifierOk returns a tuple with the BuyerExternalIdentifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardRequest) GetBuyerExternalIdentifierOk() (*string, bool) {
	if o == nil || o.BuyerExternalIdentifier == nil {
		return nil, false
	}
	return o.BuyerExternalIdentifier, true
}

// HasBuyerExternalIdentifier returns a boolean if a field has been set.
func (o *CardRequest) HasBuyerExternalIdentifier() bool {
	if o != nil && o.BuyerExternalIdentifier != nil {
		return true
	}

	return false
}

// SetBuyerExternalIdentifier gets a reference to the given string and assigns it to the BuyerExternalIdentifier field.
func (o *CardRequest) SetBuyerExternalIdentifier(v string) {
	o.BuyerExternalIdentifier = &v
}

// GetRedirectUrl returns the RedirectUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CardRequest) GetRedirectUrl() string {
	if o == nil || o.RedirectUrl.Get() == nil {
		var ret string
		return ret
	}
	return *o.RedirectUrl.Get()
}

// GetRedirectUrlOk returns a tuple with the RedirectUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CardRequest) GetRedirectUrlOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.RedirectUrl.Get(), o.RedirectUrl.IsSet()
}

// HasRedirectUrl returns a boolean if a field has been set.
func (o *CardRequest) HasRedirectUrl() bool {
	if o != nil && o.RedirectUrl.IsSet() {
		return true
	}

	return false
}

// SetRedirectUrl gets a reference to the given NullableString and assigns it to the RedirectUrl field.
func (o *CardRequest) SetRedirectUrl(v string) {
	o.RedirectUrl.Set(&v)
}
// SetRedirectUrlNil sets the value for RedirectUrl to be an explicit nil
func (o *CardRequest) SetRedirectUrlNil() {
	o.RedirectUrl.Set(nil)
}

// UnsetRedirectUrl ensures that no value is present for RedirectUrl, not even an explicit nil
func (o *CardRequest) UnsetRedirectUrl() {
	o.RedirectUrl.Unset()
}

func (o CardRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["method"] = o.Method
	}
	if true {
		toSerialize["number"] = o.Number
	}
	if true {
		toSerialize["expiration_date"] = o.ExpirationDate
	}
	if o.SecurityCode.IsSet() {
		toSerialize["security_code"] = o.SecurityCode.Get()
	}
	if o.ExternalIdentifier.IsSet() {
		toSerialize["external_identifier"] = o.ExternalIdentifier.Get()
	}
	if o.BuyerId != nil {
		toSerialize["buyer_id"] = o.BuyerId
	}
	if o.BuyerExternalIdentifier != nil {
		toSerialize["buyer_external_identifier"] = o.BuyerExternalIdentifier
	}
	if o.RedirectUrl.IsSet() {
		toSerialize["redirect_url"] = o.RedirectUrl.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableCardRequest struct {
	value *CardRequest
	isSet bool
}

func (v NullableCardRequest) Get() *CardRequest {
	return v.value
}

func (v *NullableCardRequest) Set(val *CardRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCardRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCardRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCardRequest(val *CardRequest) *NullableCardRequest {
	return &NullableCardRequest{value: val, isSet: true}
}

func (v NullableCardRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCardRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


