name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.3

      - name: Run tests
        env: 
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          go test -v
